on:
  push:
    branches:
      - main
jobs:
  build-production:
    name: Build Laravel Application
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: NPM Build
        run: |
          composer install