name: Deploy Development
on:
  push:
    branches: [ development ]
jobs:
  name: Build Application
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: | 
          git checkout main
          git pull origin main

      - name: Install Composer dependencies
        run: rm -rf vendor
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear
      
      - name: CLear Cache
        run: php artisan optimize

